name: Get Link From Telegram Input
on:
  workflow_dispatch:
    inputs:
      match_url:
        description: 'Dán link trận đấu'
        required: true
      match_name:
        description: 'Nhập tên trận đấu (Ví dụ: MU vs Barca)'
        required: true
        default: 'Canal+ Sport'

jobs:
  check_link:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install requests yt-dlp
      - name: Run script
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          MATCH_URL: ${{ github.event.inputs.match_url }}
          MATCH_NAME: ${{ github.event.inputs.match_name }} # Thêm dòng này
        run: python script.py
