name: Get Link From Telegram Input
on:
  workflow_dispatch:
    inputs:
      match_url:
        description: 'Dán link trận đấu'
        required: true
      match_name:
        description: 'Nhập tên trận đấu (Ví dụ: MU vs Barca)'
        required: true
        default: 'Canal+ Sport'

jobs:
  check_link:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests yt-dlp selenium webdriver-manager

      - name: Setup Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run script
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_WORKER_NAME: ${{ secrets.CF_WORKER_NAME }} # THÊM DÒNG NÀY
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          MATCH_URL: ${{ github.event.inputs.match_url }}
          MATCH_NAME: ${{ github.event.inputs.match_name }}
        run: python p2.py
