name: Test Get Link
on:
  workflow_dispatch: # Dòng này tạo nút bấm "Run workflow" để bạn chạy thủ công

jobs:
  check_link:
    runs-on: ubuntu-latest
    steps:
      - name: Lay code tu Github
        uses: actions/checkout@v3

      - name: Cai dat Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Cập nhật lên 3.10 để tránh lỗi cũ

      - name: Cai dat thu vien can thiet
        run: pip install requests yt-dlp

      - name: Bat dau chay code Python va Cap nhat Gist
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}      # Thêm dòng này
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}  # Thêm dòng này
        run: python script.py
